print("print(\"print(\\\"print(\\\\\\\"print(\\\\\\\\\\\\\\\"hello world\\\\\\\\\\\\\\\")\\\\\\\")\\\")\")")
print("print(\"print(\\\"print(\\\\\\\"hello world\\\\\\\")\\\")\")")
print("print(\"print(\\\"hello world\\\")\")")
print("print(\"hello world\")")
print("hello world")
